language: node_js

node_js:
  - 14

services:
  - docker

env:
  - HUGO_DEPLOY_ENV=stage
  
before_script:
  - npm install

script:
  - bash build.sh

deploy:
  - provider: script
    script: bash deploy-dev.sh
    skip_cleanup: true
    on:
      branch: main