---
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.78.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo -b https://oversizedhat.github.io/oscarberg.com-dev

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: main