language: node_js

node_js:
  - 14

services:
  - docker

env:
  - HUGO_DEPLOY_ENV=stage
  
before_script:
  - npm ci

script:
  - npm run compile
  - npm run lint:postbuild

deploy:
  - provider: script
    script: npm run deploy:dev
    skip_cleanup: true
    on:
      branch: npm