baseURL = ""
languageCode = "en-us"
title = "Oscar Berg"
publishDir = "docs"
theme = "oscar"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "post"
    url = "/posts/"
    weight = 2
#  [[menu.main]]
#    name = "Tags"
#    pre = "tag"
#    url = "/tags/"
#    weight = 3