baseURL = ""
languageCode = "en"
title = "Oscar Wendelin Berg"
publishDir = "docs"
theme = "oscar"
pluralizeListTitles = false
enableEmoji = true
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  owner = "Oscar Wendelin Berg"
  projectSource = "https://github.com/oversizedhat/oscarberg.com"
  contact64 = "b3NjYXJAb3NjYXJiZXJnLmNvbQ=="
  contactLinkedIn = "https://www.linkedin.com/in/bergoscar"
  contactGithub = "https://github.com/oversizedhat"
  googleAnalyticsMesurementId = "G-SKB7HW5GSZ"

[menu]
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 2