baseURL = ""
languageCode = "en"
title = "Oscar Wendelin Berg"
publishDir = "target"
theme = "oscar"
pluralizeListTitles = false
enableEmoji = true
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  owner = "Oscar Wendelin Berg"
  blogBanner = "I try to motivate myself to write about my own learnings. The quest for clean and simple that could be useful for others (or my future self). A lot of it workflow related..."
  projectSource = "https://github.com/oversizedhat/oscarberg.com"
  contact64 = "b3NjYXJAb3NjYXJiZXJnLmNvbQ=="
  contactLinkedIn = "https://www.linkedin.com/in/bergoscar"
  contactGithub = "https://github.com/oversizedhat"
  googleAnalyticsMesurementId = "G-SKB7HW5GSZ"

[menu]
  [[menu.main]]
    name = "Blog"
    pre = "blog"
    url = "/blog/"
    weight = 2

[module]
  [[module.mounts]]
    source = "./node_modules/bootstrap/dist/css"
    target = "./assets/css/bootstrap"