  server:
    image: klakegg/hugo:ext-alpine
    environment:
      - "DEV_SERVER_PRIVATE_IP=${DEV_SERVER_PRIVATE_IP}"
      - "HUGO_FLAGS=${HUGO_FLAGS}"
    command: server --port 8080 -b $DEV_SERVER_PRIVATE_IP $HUGO_FLAGS
    volumes:
      - ".:/src"
    ports:
      - "8080:8080"