  server:
    image: klakegg/hugo
    environment:
      - "DEV_SERVER_PRIVATE_IP=${DEV_SERVER_PRIVATE_IP}"
    command: server --port 8080 -b $DEV_SERVER_PRIVATE_IP
    volumes:
      - ".:/src"
    ports:
      - "8080:8080"